linters:
  enable:
    - gofumpt
    - gosec
    - lll
    - prealloc
    - misspell
    - nakedret
    - unparam
    - bodyclose
    - interfacer
    - unconvert
    - maligned
    - scopelint
    - gocritic
    - sqlclosecheck
    - bodyclose
    - dogsled
    - errorlint
    - exhaustive
    - exportloopref
    - gocyclo
    - godot
    - staticcheck
    - unconvert
    - stylecheck
#    - gocognit
#    - nestif


linters-settings:
  goimports:
    local-prefixes: github.com/gokhantamkoc
  lll:
    line-length: 120
    tab-width: 5
