name: CI - Notify PR to Discord Channel
on:
  pull_request:
    branches: 
      - master
jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - name: Load Discord Webhook Library
          uses: appleboy/discord-action@0.0.3
        - name: Load Pull Request
          uses: repo-sync/pull-request@v2
        - name: Notify Action
          run: echo "Sending message to discord"
        - name: Send PR notification message to Discord Channel
          with:
            # discord webhook id
            webhook_id: ${{ secrets.DISCORD_PR_REQUESTS_WEBHOOK_ID }}
            # discord webhook token
            webhook_token: ${{ secrets.DISCORD_PR_REQUESTS_WEBHOOK_TOKEN }}
            color: "#48f442"
            message: |
              A PR has been opened for growth-framework  
              URL: ${{steps.open-pr.outputs.pr_url}}
              #: ${{steps.open-pr.outputs.pr_number}}
