- name: CI - Notify PR to Discord Channel
  uses: appleboy/discord-action@0.0.3
  on:
    pull_request:
      branches: 
        - master
  with:
    # discord webhook id
    webhook_id: 849938378282631169
    # discord webhook token
    webhook_token: EROHxk-QEdEn0WyXb8_A211W-RiKUWIKseDiuzD0AyqNaLaWuoMOxj1kn65P4zpBYLDg
    message: "A PR has been opened for growth-framework"
