name: CI - Notify PR to Discord Channel
on:
  pull_request:
    branches: 
      - master
jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - uses: 8BitJonny/gh-get-current-pr@1.1.0
        id: PR
        with:
          github-token: ${{ secrets.GH_TKN }}
          # Only return if PR is still open
          filterOutClosed: true
        env:
          PR_NO: ${{ steps.PR.outputs.number }}
          PR_TITLE: ${{ steps.PR.outputs.pr_title }}
          PR_URL: ${{ steps.PR.outputs.pr_url }}
      - name: Notify Action
        run: echo "Sending message to discord"
      - name: Send PR notification message to Discord Channel
        uses: appleboy/discord-action@0.0.3
        with:
          # discord webhook id
          webhook_id: ${{ secrets.DISCORD_PR_REQUESTS_WEBHOOK_ID }}
          # discord webhook token
          webhook_token: ${{ secrets.DISCORD_PR_REQUESTS_WEBHOOK_TOKEN }}
          color: "#48f442"
          message: |
            > A PR has been opened for growth-framework
            **#:** ${{ PR_NO }}
            **Title:** ${{ PR_TITLE }}
            **URL:** ${{ PR_URL }}
